# Each world is sliced up like this:
# ^           ______
# | -z       |      |
# | n        | top  |
# | o  ______|______|______ ______
# | r |      |      |      |      |
# | t | left | front| right| back |
# | h |______|______|______|______|
# |--        |      |
# | s        |bottom|
# | o        |______|
# | u
# | t
# | h
# | +z
# \/
#    west        east
# <--- -x ----- +x ----------->
#
# with layers stacked. The only thing you can configure is the "edge size" globally, which then adjusts all other maths.
#
debug: true
# edge size is in chunks
edge: 10
#worlds:
# earth:
#  layers:
#   spawn-layer1:
#    world: world
#    spawn: true
#    launch: true
#    connect:
#     top: sky-layer1
#     bottom: cave-layer1
#   cave-layer1:
#    world: world-cave
#    spawn: false
#    launch: false
#    connect:
#     top: spawn-layer1
#     bottom: hell
#   sky-layer1:
#    world: world-sky
#    spawn: false
#    launch: true
#    connect:
#     bottom: spawn-layer1
#   hell:
#    world: world-nether
#    spawn: false
#    launch: false
#    connect:
#     top: cave-layer1
#  distance-from-sun: 149597870700 